# Generated by Django 5.2 on 2025-04-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_book_language_book_physical_format_book_publishers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
