# Generated by Django 5.2 on 2025-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
