# Generated by Django 5.2 on 2025-04-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
