# Generated by Django 5.2 on 2025-04-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_initial'),
        ('libraries', '0003_alter_store_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='book',
        ),
        migrations.AddField(
            model_name='borrow',
            name='storeContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.storecontent'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='storeContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.storecontent'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='borrow_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
