# Generated by Django 5.2 on 2025-04-23 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_remove_borrow_book_remove_borrowrequest_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_date',
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
