# Generated by Django 5.2 on 2025-04-22 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_alter_store_phone'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='book',
        ),
        migrations.AddField(
            model_name='order',
            name='storeContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.storecontent'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='storeContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.storecontent'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('storeContent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.storecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
