# Generated by Django 5.2 on 2025-04-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_book_remove_orderrequest_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
